### ISSUE TITLE
Schedule value in SchedulePolicy should be more structured

### ISSUE THREAD

**Issue by lpabon** [libopenstorage/openstorage#459]
**Is this a BUG REPORT or FEATURE REQUEST?**:
REQUEST

**What happened**:
The value of SchedulePolicy.Schedule is a string which is a yaml. Being an unstructured string makes it difficult for developers to know what to pass in and to create the objects. Instead of encoding a yaml in a string, the schedule itself could have the defined structure.

Part of #407

**Comment by ram-infrac** [comment]
@lpabon  How about using schedule package in openstorage(pkg/sched) to allow developer marshal and unmarshal  schedule yaml string?
we can provide separate utility module with SDK with such utils functionality which will also include different  conversion methods
**For eg.** ```CreateCloudSnapshot``` does not provide backup id so that developer has to enumerate and match id with volume and perform further operation like restore/delete etc.
Utility module will include functions which allow developer to pass volume name and get cloudbackup ID. We can identify such task in SDK and start providing functionality.

What do you think @lpabon? Is it feasible in scope or too vast idea
