### ISSUE TITLE
add new name field in api for creds

### ISSUE THREAD

**Issue by sdeoras** [libopenstorage/openstorage#569]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:
we need an ability to manage creds based on name. currently creds are being managed using a uuid, which can be inconvenient. so we need a new constant to access name.

**What you expected to happen**:
Add new const for name around here:
https://github.com/libopenstorage/openstorage/blob/master/api/api.go#L72

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lpabon** [comment]
Currently the SDK does not take `name` as a value to [`Credentials.Create()`](https://libopenstorage.github.io/w/generated-api.html#methodopenstorageapiopenstoragecredentialscreate). How would this be used? Would name have to be required and passed in to Create() function?

If `name` was part of Create(), then, a name2uuid function must be created because if not this breaks the entire SDK as it currently stands.

**Comment by sdeoras** [comment]
yes name will be passed at the time of creation and will be stored against uuid as a field. during lookup by name, all creds will be enumerated and name will be searched.

**Comment by lpabon** [comment]
Discussed it offline. Due to `name` having to be unique across all credentials, it will be used for idempotency and for Enumerate calls. Here are the tasks that are needed:

#### SDK Changes

* `name` will be added to `SdkCredentialCreateRequest`. This item must be provided.
* API Call `Inspect()` would have to be changed to use **oneof** to and in it would have the `credential_uuid` or `name`
* SdkCredentialInspectResponse would need to have `name`.

#### Golang interface changes

* New map key needed to use for `name`

That should be it.
