### ISSUE TITLE
Repo reorganization

### ISSUE THREAD

**Issue by peter-edge** [libopenstorage/openstorage#82]
I like having a cleaner top-level structure for repos. It makes working with go a lot nicer, and splits source code from everything else.

Some examples:
- github.com/pachyderm/pachyderm - `src` contains all go code, `etc` contains everything else, `vendor` has all vendoring, `doc` has all docs. `etc` would contain things like the yaml files at the top level, and the osd.service file.
github.com/peter-edge/flightaware - instead of `src`, this splits up code by language for when you may have multiple languages. I am starting to personally prefer this style, especially if a repo is expected to expose a public API in the future and you might want to auto-generate sdks for the library. This repo would also have an `etc` directory, but `vendor` is under `go`.

Thoughts?

**Comment by jvinod** [comment]
etc, doc dirs SGTM ..I'd punt on the 'go' src dir ..

**Comment by peter-edge** [comment]
etc is added in https://github.com/libopenstorage/openstorage/commit/8d07329468ef709838e443dc17b1eecf2c7cf77d

on docs, we have README.md files all over the place, we should centralize these, what do you think?

I am hugely in favor of a src/ dir, it makes stuff really nice in the long term for a bigger project like this, can we discuss that more?

**Comment by gourao** [comment]
Regarding having README.md in each directory, I think that actually is more explanatory instead of one mega README file.  The top level README needs to be cleaned up, the diagrams fixed to explain the overall architecture.

Then in each sub directory (at least the major ones which are `volume`, `graph`, `api` and `cluster`, we need to have sub READMEs that describe the purpose of those modules.

Finally, in each driver provider (for `graph` and `volume`), there should be specific READMEs that describe how to use that driver and it's dependancies on the main `config.yaml` file.

**Comment by gourao** [comment]
Closing
